# Use root/example as user/password credentials
version: '3.1'

services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 9001:8080

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3307:3307